### ISSUE TITLE
Range generator

### ISSUE THREAD

**Issue by jcornaz** [jcornaz/kwik#184]
I'd like to have a range generator.

The API could look like this:

```kotlin
fun <T> Generator.Companion.ranges(gen: Generator<T>): Generator<ClosedRange<T>>= TODO()
```

For the samples I am thinking about:

* empty range (`endInclusive < start`) *EDIT: Only for concrete ranges such as `IntRange` or similar.*
* single element range (`endInclusive == start`)
* ~~`start` and/or `endInclusive` being sample of the underlying generator~~ *EDIT:  We cannot explicitly query for samples anymore. We can only delegate generation to the unerlying generator which will have higher probability to return its samples.*

**Comment by Kantis** [comment]
I took a stab at this one but believe it's a bit tricky. The primary issue I'm running into is that `ClosedRange` does not provide any way to construct the empty range. 

I also tried approaching it by creating a generic function as such
```
fun <T> createEmptyRange(item: T): ClosedRange<T>? =
    when (item) {
        is Int -> 1..0
        is Char -> 'B'..'A'
    }
``` 

But it doesn't work due to upcasting not being accepted, not sure why. This approach also requires the generation of a seeding item, which feels a bit ugly.

Could implemnenting it as explicitly typed range generators be acceptable? e.g. `fun Generator.Companion.intRanges(gen: Generator<Int> = ints()): Generator<IntRange> = TODO()`

**Comment by jcornaz** [comment]
Hi @Kantis, Thanks for looking at this.

> Could implemnenting it as explicitly typed range generators be acceptable?

A generator for ÌntRange would be great and you can definitely go for it.

However, I still think that a generator of generic `ClosedRange<T>` would be nice.

I do see the problem for generating samples for a generic `ClosedRange<T>` though. My approach would be to not simply not automatically include samples for the generic ranges. The user will have to explicitly call `withSamples()` defining relevant edge cases for the test at hand.
